### ISSUE TITLE
Add a "Clear" button

### ISSUE THREAD

**Issue by WillPaulRyan** [WillPaulRyan/emoji-speller#1]
Above the "Copy" button, to clear the user input line.

**Comment by hylickipiotr** [comment]
I would like to add 'Clear' button 😀👏

**Comment by WillPaulRyan** [comment]
Hi @nexus0212, go for it!

**Comment by WillPaulRyan** [comment]
@nexus0212 Check out the commit I've just made to the master

**Comment by WillPaulRyan** [comment]
@nexus0212 I've made a suggestion of what to do, but feel free to implement what you had in mind

**Comment by hylickipiotr** [comment]
@WillPaulRyan I thought you needed help with this project. I see that you have your idea for this project, and it is simpler than mine. But if you ever need some help, I am open to help you 😀

**Comment by WillPaulRyan** [comment]
@nexus0212 Cheers, man
